config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#top'
  get 'about' => 'home#about'
  get 'login' => 'users#login_form', as: :login
  post 'login' => 'users#login'
  post 'logout' =>'users#logout', as: :logout
  get 'users/:id/likes' => 'users#likes'
  resources :reviews
  resources :users
  resources :likes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  review_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_likes_on_review_id  (review_id)
#  index_likes_on_user_id    (user_id)
#
class Like < ApplicationRecord
  validates :user_id, presence: true
  validates :review_id, presence: true

  belongs_to :user
  belongs_to :review
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :integer          not null, primary key
#  others     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_reviews_on_user_id  (user_id)
#
class Review < ApplicationRecord
  validates :others, presence: true, length: {maximum: 140}
  validates :user_id, presence: true

  belongs_to :user, dependent: :destroy
  has_many :likes, dependent: :destroy

  # def user
  #   return User.find_by(id: self.user_id)
  # end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  password   :string
#
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { maximum: 100}
  validates :email, presence: true, uniqueness: true, length: { maximum: 255}
  # validates :password, presence: true

  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    # @current_user = User.find(session[:user_id])
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to "/login"
    end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to  reviews_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user, only: [:top]
  def top
  end

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    @like = Like.new(
      user_id: @current_user.id,
      review_id: params[:review_id]
    )
    @like.save
    redirect_to review_path(@like.review_id)
  end

  def destroy
    @like = Like.find_by(
      user_id: @current_user.id,
      review_id: params[:id]
    )
    @like.destroy
    redirect_to review_path(@like.review_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @reviews = Review.all.order(created_at: :desc)
  end

  def show
    @review = Review.find(params[:id])
    @user = @review.user
    @already_liked = @review.likes.exists?(user_id: @current_user.id)
  end

  def new
      @review = Review.new
  end

  def create
    @review = Review.new(create_params)
    @review.user_id = @current_user.id
    if @review.save
      flash[:notice] = "レビューを投稿しました"
      redirect_to reviews_path
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.others = params[:others]
    if @review.save
      flash[:notice] = "レビューを編集しました"
      redirect_to reviews_path
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "レビューを削除しました"
    redirect_to reviews_path
  end

  def ensure_correct_user
    @review = Review.find(params[:id])
    if @review.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to reviews_path
    end
  end

  private
  def create_params
    params
      .require(:review)
      .permit(
        :others
      )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index, :show, :edit, :update]
  before_action :forbid_login_user, only: [:new, :create, :login_form, :login]
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザ登録が完了しました"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(update_params)
      flash[:notice] ="ユーザ情報を編集しました"
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "ユーザを削除しました"
    redirect_to users_path
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to reviews_path
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render :login_form
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to login_url
  end

  def likes
    @user = User.find(params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to reviews_path
    end
  end

  private
  def create_params
    params
      .require(:user)
      .permit(
        :name,
        :email,
        :password
      )
  end

  def update_params
    params
      .require(:user)
      .permit(
        :name,
        :email
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<style>
  .about .about-message {
    text-align: center;
  }
  .about .about-message h1 {
    font-size: 50px;
  }
  .about .about-message p {
    font-size: 20px;
  }
</style>

<div class="main about">
  <div class="about-message">
    <h1>About REVIEW APP</h1>
    <p>Bla bla bla...</p>
  </div>
</div>

app/views/home/top.html.erb
<style>
  .top .top-message {
    text-align: center;
  }
  .top .top-message h1 {
    font-size: 50px;
  }
  .top .top-message p {
    font-size: 20px;
  }
</style>

<div class="main top">
  <div class="top-message">
    <h1>REVIEW APP</h1>
    <p>Lets review in detail!</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header>
      <div class="header-container">
        <div class="header-logo">
          <% if @current_user %>
            <h1><%= link_to("REVIEW APP", reviews_path) %></h1>
          <% else %>
            <h1><%= link_to("REVIEW APP", "/") %></h1>
          <% end %>
        </div>
        <ul class="header-menus">
          <% if @current_user %>
            <li>
              <%= link_to(@current_user.name, user_path(@current_user.id)) %>
            </li>
            <li><%= link_to("レビューリスト", reviews_path) %></li>
            <li><%= link_to("ユーザリスト", users_path)  %></li>
            <li><%= link_to("レビューする", new_review_path) %></li>
            <li><%= link_to("ログアウト", logout_url, {method: :post}) %></li>
          <% else %>
            <li><%= link_to("REVIEW APPとは", "/about") %></li>
            <li><%= link_to("新規登録", new_user_path) %></li>
            <li><%= link_to("ログイン", login_url) %></li>
          <% end %>
        </ul>
      </div>
    </header>

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<style>
  .form .form-body {
    text-align: center;
  }
  .reviews-edit h1 {
    text-align: center;
    margin-bottom: 50px;
  }
  .reviews-edit textarea {
    font-size: 20px;
    padding: 10px;
    min-height: 140px;
    border: 1px solid rgb(216, 218, 223);
    resize: none;
  }
  .reviews-edit input {
    display: block;
    margin: 0 auto;
    background-color: #ee8070;
    color: white;
    cursor: pointer;
    width: 120px;
    margin-top: 20px;
    height: 45px;
  }
</style>


<div class="main reviews-edit">
  <div class="container">
    <h1>編集する</h1>
    <%= form_tag(review_path, method: :put) do %>
      <div class="form">
        <div class="form-body">
          <% @review.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <textarea name="others">
            <%= @review.others %>
          </textarea>
          <input type="submit" value="保存">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<style>
  .reviews-index .review-index-item {
    padding: 20px 30px;
    margin: 20px 50px;
    overflow: hidden;
    box-shadow: 0 2px 6px #c1ced7;
  }
  .reviews-index .review-index-item a {
    display: block;
    width: inherit;
  }
  .reviews-index .review-index-item .review-user-name a{
    color: #ee8070;
  }
  .reviews-index .review-index-item .review-others {
    color: black;
    font-size: 14px;
  }

</style>

<div class="main reviews-index">
  <div class="container">
    <% @reviews.each do |review| %>
      <div class="review-index-item">
        <div class="review-user-name">
          <% if review.user.present? %>
            <%= link_to(review.user.name, user_path(review.user)) %>
          <% else %>
            <p>--</p>
          <% end %>
        </div>
        <div class="review-others">
          <% if review.user.present? %>
            <%= link_to(review.others, review_path(review)) %>
          <%else%>
            <%= review.others %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<style>
  .form .form-body {
    text-align: center;
  }
  .reviews-new h1 {
    text-align: center;
    margin-bottom: 50px;
  }
  .reviews-new textarea {
    font-size: 20px;
    padding: 10px;
    min-height: 140px;
    border: 1px solid rgb(216, 218, 223);
    resize: none;
  }
  .reviews-new input {
    display: block;
    margin: 0 auto;
    background-color: #ee8070;
    color: white;
    cursor: pointer;
    width: 120px;
    margin-top: 20px;
    height: 45px;
  }
</style>

<div class="main reviews-new">
  <div class="container">
    <h1>投稿する</h1>
    <%= form_for @review do |f| %>
      <div class="form">
        <div class="form-body">
          <% @review.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <%= f.text_area :others %>
          <%= f.submit '投稿' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<style>
  .reviews-show .review-show-item {
    padding: 20px 30px;
    margin: 20px 50px;
    overflow: hidden;
    box-shadow: 0 2px 6px #c1ced7;
  }
  .reviews-show .review-show-item .review-user-name {
    font-size: 30px;
    color: #ee8070;
  }
  .reviews-show .review-show-item .review-body {
    color: black;
    font-size: 20px;
    margin: 20px 0;
  }
  .reviews-show .review-show-item .review-menus {
    display: flex;
    justify-content: space-between;
  }
  .reviews-show .review-show-item .review-menus .edit-bar a {
    color: #8899a6;
    text-decoration: underline;
    margin: 0 10px;
  }
  .reviews-show .review-show-item .review-menus .like .fa{
    font-size: 25px;
  }
  .reviews-show .review-show-item .review-menus .like .like-btn-unlike {
    color: #E54932;
  }
.reviews-show .review-show-item .review-menus .like .like-btn {
  color: #8899a6;
}

</style>

<div class="main reviews-show">
  <div class="container">
    <div class="review-show-item">
      <div class="review-user-name">
        <%= link_to(user_path(@user)) do %>
          <p><%= @user.name %></p>
        <% end %>
      </div>
      <div class="review-body">
        <p>
          <%= @review.others %>
        </p>
      </div>
      <div class="review-time">
        <p>
          <%= @review.created_at %>
        </p>
      </div>
      <div class="review-menus">
        <div class="like">
          <% if @already_liked %>
            <%= link_to(like_path, method: :delete) do %>
              <span class="fa fa-heart like-btn-unlike"></span>
            <% end %>
          <% else %>
            <%= link_to(likes_path(review_id: @review.id), method: :post) do %>
              <span class="fa fa-heart like-btn"></span>
            <% end %>
          <% end %>
        </div>
        <div class="edit-bar">
          <% if @review.user_id == @current_user.id %>
            <%= link_to("編集", edit_review_path) %>
            <%= link_to("削除", review_path, method: :delete, data: {confirm: "レビューを削除しますか？"}) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<style>
  .users-edit .form-heading {
    text-align: center;
    margin-bottom: 50px;
  }
  .users-edit .form-body {
    text-align: center;
  }
  .users-edit .form-body input {
    margin-bottom: 20px;
    border: 1px solid rgb(216, 218, 223);
  }
  .users-edit .form-body .user-edit-input {
    display: block;
    margin: 0 auto;
    background-color: #ee8070;
    color: white;
    cursor: pointer;
    width: 120px;
    height: 45px;
    border: none;
}
</style>

<div class="main users-edit">
  <div class="container">
    <div class="form-heading">
      <h1>ユーザ情報の編集</h1>
    </div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_tag(user_path, method: :put) do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">
          <input class="user-edit-input" type="submit" value="保存">
        <% end %>
          </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<style>
.users-index .users-heading {
  margin-bottom: 20px;
}
.users-index .users-index-item {
  padding: 20px 30px;
  background-color: white;
  overflow: hidden;
  box-shadow: 0 2px 6px #c1ced7;
  display: table;
  width: 100%
}
.users-index .users-index-item a {
  display: block;
  width: inherit;
}
</style>

<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザ一覧</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-name">
        <%= link_to(user_path(user)) do %>
          <%= user.name %>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<style>
  .user-show .user {
    text-align: center;
  }
  .user-show .user a {
    color: #8899a6;
    text-decoration: underline;
    margin: 0 10px;
  }.user-show .review-index-item {
    padding: 20px 30px;
    overflow: hidden;
    box-shadow: 0 2px 6px #c1ced7;
  }
  .user-show .review-index-item a {
    display: block;
    width: inherit;
  }
  .user-show .review-index-item .review-user-name a{
    color: #ee8070;
  }
  .user-show .review-index-item .review-others {
    color: black;
    font-size: 14px;
  }
  .user-tabs {
  margin-top: 40px;
  background-color: white;
  overflow: hidden;
  box-shadow: 0 2px 6px #c1ced7;
  }
.user-tabs li {
  float: left;
}
.user-tabs li.active {
  border-bottom: 2px solid #70D1E0;
}
.user-tabs li.active a {
  color: #57575f;
}
.user-tabs a {
  display: inline-block;
  padding: 16px 30px;
  color: #afb6bf;
}
</style>

<div class="main user-show">
  <div class="container">
    <div class="user">
      <h1><%= @user.name %></h1>
      <p><%= @user.email %></p>
        <% if @user.id == @current_user.id %>
          <%= link_to("編集", edit_user_path) %>
          <%= link_to("削除", user_path, method: :delete, data: {confirm: "#{@user.name}を削除しますか？"}) %>
        <% end %>
    </div>
    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", user_path(@user.id)) %></li>
      <li><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    <% @likes.each do |like| %>
      <div class="review-index-item">
        <div class="review-user-name">
          <%= like.review.user.name %>
        </div>
        <div class="review-others">
          <%= like.review.others %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<style>
  .users-login .form-heading {
    text-align: center;
    margin-bottom: 50px;
  }
  .users-login .form-body {
    text-align: center;
  }
  .users-login .form-body input {
    margin-bottom: 20px;
    border: 1px solid rgb(216, 218, 223);
  }
  .users-login .form-body .user-login-input {
    display: block;
    margin: 20px auto;
    background-color: #ee8070;
    color: white;
    cursor: pointer;
    width: 120px;
    height: 45px;
    border: none;
  }
</style>

<div class="main users-login">
  <div class="container">
    <div class="form-heading">
      <h1>ログイン</h1>
    </div>
    <div class="form users-form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
        <%= form_tag("/login") do %>
          <p>メールアドレス</p>
          <input name="email" value="<%= @email %>">
          <p>パスワード</p>
          <input name="password" type="password" value="<%= @password %>">
          <input class="user-login-input" type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<style>
  .users-new .form-heading {
    text-align: center;
    margin-bottom: 50px;
  }
  .users-new .form-body {
    text-align: center;
  }
  .users-new .form-body label {
    display: block;
  }
  .users-new .form-body input {
    display: block;
    margin: 0 auto 20px;
    border: 1px solid rgb(216, 218, 223);
  }
  .users-new .form-body .user-new-input {
    display: block;
    margin: 50px auto;
    background-color: #ee8070;
    color: white;
    cursor: pointer;
    width: 120px;
    height: 45px;
    border: none;
  }
</style>

<div class="main users-new">
  <div class="container">
    <div class="form-heading">
      <h1>新規ユーザ登録</h1>
    </div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_for @user do |f| %>
          <%= f.label :name, "ユーザ名" %>
          <%= f.text_field :name %>
          <%= f.label :email, "メールアドレス" %>
          <%= f.text_field :email %>
          <%= f.label :password, "パスワード" %>
          <%= f.text_field :password %>
          <%= f.submit '新規登録', class: "user-new-input" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<style>
  .user-show .user {
    text-align: center;
  }
  .user-show .user a {
    color: #8899a6;
    text-decoration: underline;
    margin: 0 10px;
  }
  .user-show .review-index-item {
    padding: 20px 30px;
    overflow: hidden;
    box-shadow: 0 2px 6px #c1ced7;
  }
  .user-show .review-index-item a {
    display: block;
    width: inherit;
  }
  .user-show .review-index-item .review-user-name a{
    color: #ee8070;
  }
  .user-show .review-index-item .review-others {
    color: black;
    font-size: 14px;
  }

  .user-tabs {
  margin-top: 40px;
  background-color: white;
  overflow: hidden;
  box-shadow: 0 2px 6px #c1ced7;
}

.user-tabs li {
  float: left;
}

.user-tabs li.active {
  border-bottom: 2px solid #70D1E0;
}

.user-tabs li.active a {
  color: #57575f;
}

.user-tabs a {
  display: inline-block;
  padding: 16px 30px;
  color: #afb6bf;
}

</style>

<div class="main user-show">
  <div class="container">
    <div class="user">
      <h1><%= @user.name %></h1>
      <p><%= @user.email %></p>
        <% if @user.id == @current_user.id %>
          <%= link_to("編集", edit_user_path) %>
          <%= link_to("削除", user_path, method: :delete, data: {confirm: "#{@user.name}を削除しますか？"}) %>
        <% end %>
    </div>
    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", user_path(@user.id)) %></li>
      <li><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
      <% @user.reviews.each do |review| %>
        <div class="review-index-item">
          <div class="review-user-name">
            <%= link_to(review.user.name, user_path(review.user)) %>
          </div>
          <div class="review-others">
            <%= review.others %>
          </div>
        </div>
      <% end %>
  </div>
</div>